services:
  mongo:
    image: mongo:8.0.15
    container_name: mongo115200
    restart: "no"

    command:
      - mongod
      - --bind_ip_all
      - --logpath
      - /var/log/mongodb/mongod.log
      - --logappend
      - --setParameter
      - logLevel=5

    volumes:
      - ./data:/data/db
      - ./logs:/var/log/mongodb
