services:
  mongo101180:
    image: mongo:7.0.17
    container_name: mongo101180
    restart: "no"

    command:
      - mongod
      - --bind_ip_all
      - --logpath
      - /logs/mongod.log
      - --logappend
      - --setParameter
      - logLevel=5

    volumes:
      - ./logs:/logs
      - ./data:/data/db
