worker_processes 1;

daemon off;

pid run/nginx.pid;

# core dump
worker_rlimit_core 1G;
working_directory core;

# nginx debug log
error_log logs/error.log debug;

events {
    worker_connections 128;
}

http {
    access_log logs/access.log;

    server {
        listen 127.0.0.1:8080;

        # nginx 자체가 정상인지 확인하기 위한 endpoint
        location = /health {
            return 200 "alive\n";
        }

        # GitHub issue #983 재현용
        location /ttll/ {
            root www;

            try_files /abcd /abc12 /abc123 /abcd;

            proxy_pass http://127.0.0.1:9090/;
        }

        location /normal/ {
            root www;

            try_files /normal/abcd =404;

            proxy_pass http://127.0.0.1:9090/;
        }
    }
}
