services:
  pg-target:
    image: postgres:13.1
    container_name: pg-16801
    privileged: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      LD_PRELOAD: /libminidump.so
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql", "-c", "log_filename=output.log", "-c", "log_min_messages=debug2", "-c", "log_error_verbosity=verbose"]
    volumes:
      - ./logs:/var/log/postgresql
      - ./libminidump.so:/libminidump.so:ro
